### PR TITLE
Replace all

### LINKED ISSUE #21: Change to replace all
Currently the libray replaces only the first occurence of the placeholder.

But we need it to support replace all the occurences.

For this there should be a chane at this line

https://github.com/arshadkazmi42/strmat/blob/master/index.js#L15

To use regex with `g` to replace all.

### PR DESCRIPTION
**Pull request by sivasuriyankumarasamy**
Fixes #21

### CODE REVIEW

**Review by arshadkazmi42 — CHANGES_REQUESTED** [review]
`replaceAll` was not supported in javascript until v15 and we want to support older version also.

I will suggest using regex you can refer here for reference.

Also, I think we need to add more tests to verify this. If there are two parameters with same key which needs to be replaced should also work. We will need one test for this.

I would also suggest you to run the tests after making changes.

**Comment by sivasuriyankumarasamy** [comment]
@arshadkazmi42,
Updated as requested and added test cases as well. please review.

If you are merging this change, please add hacktoberfest-accepted label for the ticket.

**Review by arshadkazmi42 — APPROVED** [review]
LGTM :tada:

**Comment by sivasuriyankumarasamy** [comment]
Can update  hacktoberfest-accepted label so that it will be counted for hacktoberfest

**Comment by arshadkazmi42** [comment]
Added the labels. Sorry about that. I thought I already added.

**Pull request merged**
